### ISSUE TITLE
The idea is great but doesn't scale well

### ISSUE THREAD

**Issue by joaojhgs** [cerebruminc/yates#68]
This project is really interesting, but after giving it a glance, I think that it wouldn't be able to scale well, as the amount of entities grow, it becomes inviable to keep storing the "abilities" at the client setup, every new entity would require a new ability and that would end up clogging the prisma client setup file.

I think it would be great to be able to define those abilities at the prisma schema, that way we'd have a centralized yet less verbose way of doing things, similar to what RedwoodJs does with their schema authentication middleware, but instead of using code authorization, it'd use pg RLS.

What do you guys think?

**Comment by sebmellen** [comment]
Hey @joaojhgs!

Currently, we're scaling quite well with this at an enterprise level.

That said, it's certainly an interesting idea... I'm sure @LucianBuzzo would like to hear more.

How do you picture these abilities living in the `schema.prisma` file? What would that syntax look like? If you could write a quick proposal on that, we would be glad to consider it.

**Comment by LucianBuzzo** [comment]
Hi @joaojhgs there is an issue for implementing RLS directly in the schema on the Prisma repo itself - https://github.com/prisma/prisma/issues/12735
If this is something you are interested in I suggest contributing to the discussion there.
Yates exists because this functionality isn't supported natively in Prisma, and would require a big lift to implement it, especially for an outside contributor.
